server {
	# SSL Config
	listen      443 ssl;
	ssl_certificate     /etc/nginx/ssl/certificate.crt;
	ssl_certificate_key /etc/nginx/ssl/certificate.key;
	ssl_protocols       TLSv1.2 TLSv1.3;

	# root, index et server_name
	root    /var/www/html/;
	server_name 'rcompain.42.fr' www.$DOMAIN_NAME;
	index index.php;

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
        	fastcgi_pass wordpress:9000;
	}
}

