services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file: .env
    restart: on-failure
  static-site:
    container_name: static-site
    image: static-site:inception
    build: ./requirements/bonus/static-site
    networks:
      - inception
    ports:
      - "81:81"
    restart: on-failure

networks:
  inception:


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rcompain/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rcompain/data/mariadb
